/*
 * Copyright (c) 2010-2015 Osman Shoukry
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Lesser General Public License as published by
 *    the Free Software Foundation, either version 3 of the License or any
 *    later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.openpojo.random.impl;

public enum SomeEnum {
    ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, ELEVEN, TWELVE, THIRTEEN, FOURTEEN, FIFTEEN,
    SIXTEEN, SEVENTEEN, EIGHTEEN, NINETEEN, TWENTY, TWENTYONE, TWENTYTWO, TWENTYTHREE, TWENTYFOUR, TWENTYFIVE,
    TWENTYSIX, TWENTYSEVEN, TWENTYEIGHT, TWENTYNINE, THIRTY, THIRTYONE, THIRTYTWO, THIRTYTHREE, THIRTYFOUR,
    THIRTYFIVE, THIRTYSIX, THIRTYSEVEN, THIRTYEIGHT, THIRTYNINE, FORTY, FORTYONE, FORTYTWO, FORTYTHREE, FORTYFOUR,
    FORTYFIVE, FORTYSIX, FORTYSEVEN, FORTYEIGHT, FORTYNINE, FIFTY, FIFTYONE, FIFTYTWO, FIFTYTHREE, FIFTYFOUR,
    FIFTYFIVE, FIFTYSIX, FIFTYSEVEN, FIFTYEIGHT, FIFTYNINE, SIXTY, SIXTYONE, SIXTYTWO, SIXTYTHREE, SIXTYFOUR,
    SIXTYFIVE, SIXTYSIX, SIXTYSEVEN, SIXTYEIGHT, SIXTYNINE, SEVENTY, SEVENTYONE, SEVENTYTWO, SEVENTYTHREE,
    SEVENTYFOUR, SEVENTYFIVE, SEVENTYSIX, SEVENTYSEVEN, SEVENTYEIGHT, SEVENTYNINE, EIGHTY, EIGHTYONE, EIGHTYTWO,
    EIGHTYTHREE, EIGHTYFOUR, EIGHTYFIVE, EIGHTYSIX, EIGHTYSEVEN, EIGHTYEIGHT, EIGHTYNINE, NINETY, NINETYONE,
    NINETYTWO, NINETYTHREE, NINETYFOUR, NINETYFIVE, NINETYSIX, NINETYSEVEN, NINETYEIGHT, NINETYNINE, ONEHUNDRED
}